# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
  # repetitive because unfortunately Dependabot ticket for wildcard support still open:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directory: 'mysql'
    schedule:
      interval: 'weekly'
    # we may not want to switch MySQL major version without good reason
    # the version should also be the same as in staging and production
    ignore:
      - dependency-name: 'mysql'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
