version: '3.9'

services:
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
      - ./mysql/config.d:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=secret
