version: '3.9'

services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
    environment:
      - MYSQL_ROOT_PASSWORD=secret
