[package]
name = "server"
version = "0.3.65"
authors = ["Serlo Education e.V."]
license = "Apache-2.0"
edition = "2021"

[dependencies]
actix-rt = "2.0.0"
actix-service = "2.0.0"
actix-web = "4.0.0"
async-trait = "0.1.0"
chrono = { version = "0.4.0", features = ["serde"] }
chrono-tz = "0.6.0"
convert_case = "0.5.0"
dotenv = "0.15.0"
futures = "0.3.0"
itertools = "0.10.5"
md5 = "0.7.0"
rand = "0.8.5"
regex = "1.0.0"
sentry = "0.27.0"
sentry-actix = "0.27.0"
serde = "1.0.0"
serde_json = "1.0.0"
sophia = "0.7.0"
sqlx = { version = "0.5.13", features = ["chrono", "offline", "json", "mysql", "runtime-actix-native-tls"] }
thiserror = "1.0.0"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports", "async"] }
rstest = "0.16.0"
test-utils = { path="../test-utils" }

[[bench]]
name = "query_entity_metadata"
harness = false
