name: Deploy
on:
  push:
    branches:
      - main
jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            awk -F ' = ' '$1 ~ /version/ { gsub(/[\\"]/, "", $2); printf("%s",$2) }' server/Cargo.toml
  docker-image:
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: yarn
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: 274.0.0
          service_account_key: ${{ secrets.GCP_KEY_CONTAINER_REGISTRY }}
      - run: gcloud auth configure-docker
      - run: yarn --frozen-lockfile
      - run: yarn deploy
